# Generated by Django 3.0.8 on 2022-06-27 13:49

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField(blank=True, default=0, verbose_name='父级评论id')),
                ('reply_id', models.IntegerField(blank=True, default=0, verbose_name='回复id')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='评论内容')),
                ('comment_type', models.CharField(choices=[('comment', '评论'), ('reply', '回复')], default='comment', max_length=10, verbose_name='评论类型')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('mail', models.EmailField(max_length=254, verbose_name='评论用户邮箱')),
                ('nick', models.CharField(max_length=20, verbose_name='评论用户名')),
                ('to_mail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='目标用户邮箱')),
                ('to_nick', models.CharField(blank=True, max_length=20, null=True, verbose_name='目标用户名')),
                ('browser', models.CharField(blank=True, max_length=100, null=True, verbose_name='浏览器')),
                ('client', models.CharField(blank=True, max_length=100, null=True, verbose_name='客户端')),
                ('avatar', models.CharField(blank=True, max_length=200, null=True, verbose_name='头像')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示评论')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='文章')),
            ],
            options={
                'verbose_name': '评论内容',
                'verbose_name_plural': '评论内容',
                'ordering': ['post_id', 'add_time'],
            },
        ),
    ]
